- type: input
    id: location
    attributes:
      label: Code Location (Permalink)
      description: >-
        Go to the file in this repo, click the line number (Shift+Click for range), 
        press 'y' to get the permanent URL, and paste it here.
      placeholder: https://github.com/razm123/workout-logger/blob/abc1234/src/main.cs#L15
    validations:
      required: true
