name: Ignition Module Bug 🔧
description: Report a defect in the Java Ignition/Backend logic
title: "[Bug]: "
labels: ["bug", "backend", "triage"]
assignees:
  - razm123
body:
  - type: markdown
    attributes:
      value: |
        ### 🛑 Ignition Module Defect
        Please ensure logs are scrubbed of PII before posting.

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the ignition logic failed?
      options:
        - 🔥 Ignition Controller (Core Logic)
        - ⏱️ Timing Service
        - 📡 Telemetry / API
        - 💾 Database Persistence
        - 🔌 Hardware Interface
    validations:
      required: true

  - type: dropdown
    id: state
    attributes:
      label: System State
      description: What was the system doing when it failed?
      options:
        - Idle / Standby
        - Initialization (Boot)
        - Active / Running
        - Error / Fault State
        - Shutting Down
    validations:
      required: true

  - type: input
    id: jdk-version
    attributes:
      label: JDK Version
      placeholder: e.g., OpenJDK 11.0.2, Corretto 17
    validations:
      required: true

  - type: input
    id: line-range
    attributes:
      label: Suspect Line Range
      description: "Format: Start-End (The specific logic block causing the failure)"
      placeholder: "e.g. 145-160"
    validations:
      required: false

  - type: textarea
    id: stack-trace
    attributes:
      label: Stack Trace / Exception
      description: Please paste the raw Java stack trace here.
      render: java 
      placeholder: |
        java.lang.IllegalStateException: Ignition sequence failed
            at com.engine.ignition.Controller.fire(Controller.java:105)
            at com.engine.main.Loop.tick(Loop.java:42)
    validations:
      required: false

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How do we make it fail again?
      value: |
        1. Start the service with config X
        2. Send trigger signal...
        3. Observe crash...
    validations:
      required: true
